### ISSUE TITLE
Can we use this tool for any bosh deployment

### ISSUE THREAD

**Issue by Rohitverma47** [cloudfoundry-community/port-forwarding-boshrelease#3]
Do we need to change the manifest of microbosh or we need to do these changes for a specific service ?
If we are trying to open port for a specific service i.e dingo-postgresql

**Comment by jhunt** [comment]
Should be usable in any BOSH deployment, including those done by bosh-init.  The port forwarding magic is done via iptables, and is independent of whatever other releases you've loaded into your deployment (unless those make incompatible changes, which is unlikely)
