### ISSUE TITLE
deprecation and iptables feature

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/port-forwarding-boshrelease#5]
Hello,
im interested in using the iptables feature. The README indicates thats the bosh-networking release should replace this release. I dont think the raw iptables configuration as been included ?

**Comment by jhunt** [comment]
I'm still using this release and the iptables feature works great for things like BOSH-lites on vSphere / AWS.

**Comment by alexanelli** [comment]
@poblin-orange just wondering if this is still an issue; thanks again 👍

**Comment by jhunt** [comment]
@xanderrman can you take a look at the README and adjust it to reflect reality, including a discussion of the bosh-networking release?
